version: '3'
services:
  db:
    container_name: postgres_db
    image: postgres
    ports:
      - "7432:5432"
    environment:
      POSTGRES_DB: demo_db
      POSTGRES_USER: demo_user
      POSTGRES_PASSWORD: DemoUser1Pass2Qa